### ISSUE TITLE
Corrupted session state

### ISSUE THREAD

**Issue by psbrandt** [stripe/gaps#38]
## Steps to Recreate

1. Be GSuite admin
2. Create new project here: https://console.developers.google.com/apis/library
3. On same page, search for and enable **Admin SDK**, **Google+ API** and **Group Settings API**
4. Configure consent screen here: https://console.developers.google.com/apis/credentials/consent
5. Create credentials here: https://console.developers.google.com/apis/credentials
6. Select OAuth Client ID, choose **Web Application** as application type (take note of ID & secret)
7. Clone https://github.com/stripe/gaps
8. Edit `docker-compose.yml` to look like:
```yaml     
version: '2'
services:
  web:
    build: .
    ports:
      - 3500:3500
    links:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo/mongo
      - RACK_ENV=development
      - FAVICON_URL=
      - GAPS_URL=http://localhost:3500
      - ORG_DOMAIN=example.com
      - ORG_NAME=Example
      - OAUTH_CLIENT_ID=<CLIENT ID> # replace
      - OAUTH_CLIENT_SECRET=<CLIENT SECRET> # replace
      - OAUTH_REDIRECT_URL=http://localhost:3500/oauth2callback
      - SESSION_SECRET=123

  mongo:
    image: mongo
```
9. Run `docker-compose up`
10. Navigate to [http://localhost:3500/](http://localhost:3500/)
11. Click **Sign In**
12. Select GSuite admin user
13. Click **ALLOW**
14. Observe error message:

```
You seem to have corrupted session state. Try logging in again?

Looks like something went wrong :(
```
15. Be sad 😞 

### Browsers

* Safari 10.1 (12603.1.30.0.34)
* Chrome 58.0.3029.110 (64-bit) (macOS)
